sudo: required

dist: xenial

before_install:
  - ./tests/require.sh

language: python

install:
  - ./docker/install

before_script:
  - sleep 10

script:
  - ./tests/test.py fxnl --random
  - ./tests/test.py sec
  - ./tests/test.py concr
