sudo: required

dist: xenial

before_install:
  - ./test-suite/require.sh

language: python

install:
  - ./docker/install

before_script:
  - sleep 10

script:
  - ./test-suite/test fxnl --random
  - ./test-suite/test sec
  - ./test-suite/test concr
